### PR TITLE
refactor: move tooltip library to vueTippy

### PR DESCRIPTION
**Pull request by wa0x6e**
### Summary

Following #148 , this PR is migrating the Ui/Tooltip component from @floating-ui to vueTippy

### How to test

1. Go to an element with tooltip
2. Hover on to
3. It should show the tooltip on hover

Style should be the same, only library has been changed

Before/After comparison

Screenshot 2024-03-11 at 19 15 10

Screenshot 2024-03-11 at 22 36 31

## Notes

The UI/Tooltip component seems empty for now, will take more options as we add auto url later

### CODE REVIEW

**Comment by bonustrack** [comment]
Some feedback:
- Button are not aligned in space overview page:
image
- We should use the same style as previously
- We should remove the animation

**Comment by wa0x6e** [comment]
> Some feedback:
> 
> * Button are not aligned in space overview page:
> 
> image
> * We should use the same style as previously
> * We should remove the animation

- Animation removed
- For the new style, it was a @samuveth request.

**Comment by samuveth** [comment]
Not really a request, more my advice to follow the design system. But this seems to be wrong every time so I won't be doing that anymore :D

**Comment by wa0x6e** [comment]
Back to old UI

**Review by samuveth — APPROVED** [review]
tACK

**Pull request merged**
