### PR TITLE
feat: add transaction details to TransactionsListItem

### PR DESCRIPTION
**Pull request by Sekhmet**
### Summary

This PR adds expandable section for Transactions with more details (Call info, parameters, value, data).
Data is shown or hidden depending on context (for example data is only shown for raw transactions as others have parsed information available).

Closes: https://github.com/snapshot-labs/workflow/issues/185

### How to test

1. Check out this proposal or create your own (you can also access details in editor): http://localhost:8080/#/s:0cf5e.eth/proposal/0x124cc146918a5c14e1c9fd40aaa293f5780304f6b26be1a9692160d8d4d4596e
2. You can expand transactions by clicking on them.

### Screenshots

image
image
image

### CODE REVIEW

**Comment by wa0x6e** [comment]
Also closing #448 ?

**Comment by bonustrack** [comment]
Looks great! I would just add a caret on mouse hover (similar than on the proposal results when there is too many choices)

image

**Comment by Sekhmet** [comment]
@bonustrack how should that look like in Editor page? (there we have also edit/delete icons already)

**Review by bonustrack — APPROVED** [review]
Actually we can merge it like this, icon on mouse over wont work well with mobile anyway, and I dont see 3 button in editor per tx

**Pull request merged**
