### PR TITLE
feat: store per-treasury execution on proposals

### PR DESCRIPTION
**Pull request by Sekhmet**
### Summary

oSnap proposals can have separate executions for multiple treasuries.
This commit will display those in the UI as separate intities, linked to specific treasury.

Currently we read treasuries from latest metadata, this means that if one treasury is used in proposal, but then it's removed or updated when you go back to the proposal it will either show Unnamed treasury or updated name.
We should store at-proposal-time treasury details on proposal directly so we have correct version, but for now I skipped this because of TheGraph's issue we can't deploy new subgraphs.

### How to test

0. Run `VITE_ENABLED_NETWORKS=s-tn,sep yarn dev`.
1. Check two proposals (onchain and off-chain).
2. **onchain** http://localhost:8080/#/sep:0xfa463A2Bdd8d27f1b0eA99270c3c4Bb3A7B2ADeF/proposal/1
3. **onchain** http://localhost:8080/#/s-tn:0cf5e.eth/proposal/0x18b4c85fb3dba579b2714a3fcdba5ea96088f9f0a51f02002e81cc39a589d674
4. They look correct.

### Screenshots

image
image

### CODE REVIEW

**Comment by bonustrack** [comment]
Great work on the design 👏🏼 , it's looks perfect to me. I've tested with your proposal it works well, I tried with Snapshot proposals having oSnap but somehow I can't see the execution with your PR even if the treasury is linked, example here: 
https://snapshot.org/#/epochisland.eth/proposal/0xdf570852e10b377c17f6703749d5a6485e29a477340ad1e97e8698f1ea21356a
You can find more examples here: https://hub.snapshot.org/graphql?query=%7B%0A%20%20proposals%20(where%3A%20%7B%20plugins_contains%3A%20%22uma%22%20%7D)%20%7B%0A%20%20%20%20id%0A%20%20%20%20space%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%7D%0A%20%20%20%20link%0A%20%20%7D%0A%7D%0A

**Comment by Sekhmet** [comment]
I'm currently reading from `oSnap` plugin, looks like this proposal uses `safeSnap` and the format there is different.

**Comment by bonustrack** [comment]
Can you check these ones:
https://snapshot.org/#/shutterdao0x36.eth/proposal/0xcc9547b9eae7e04e1146c103f36878a01b7b4353ff9cf66c207a19223f6b07b5
https://snapshot.org/#/dao.connext.eth/proposal/0x06b58c21fb9ef2a077697916e1014c9b7b9c11226fbf1e43588ed063f4da6e15

**Comment by Sekhmet** [comment]
This one uses `safeImport` transaction type that I haven't implemented right now. Will take a look what it is.

**Review by bonustrack — APPROVED** [review]
tACK

**Pull request merged**
