### PR TITLE
feat: configure and store multiple treasuries

### PR DESCRIPTION
**Pull request by Sekhmet**
### Summary

Closes: https://github.com/snapshot-labs/sx-monorepo/issues/18

Decisions:
1. We have two sources of truth for treasuries - executions and user configured treasuries on metadata, with this PR treasuries configured in metadata are used as a "whitelist" of executors that should be displayed on UI (in both treasury as well in proposal creation). You can also add treasuries that are not linked to executor to create read only treasury (can't be used in execution).
2. We had to index additional properties on backend to be able to link executors to treasuries.

### Screenshots

UI is temporary as design were not confirmed to be final.

image
image
image

### How to test

1. Run `VITE_ENABLED_NETWORKS=sep yarn dev:full`. (it can take some time for subgraph to be in sync).
2. Interact with this space as a user (check treasury, try creating proposals): http://localhost:8080/#/sep:0x8b08aa6cdaf0bc92bb9cc6844459b2fed94249af/treasury
2. Create space on Sepolia with execution strategies (can't add them to old spaces as we don't have editor for it).
3. Set treasuries in metadata (so for timelock execution it's just strategy address, for avatar it's avatar's address).

### CODE REVIEW

**Comment by bonustrack** [comment]
Somehow I'm not able to create a Starknet Sepolia space, got this error on Argent X
```
Transaction failure predicted
ReviewError: $a: RPC: starknet_estimateFee with params {
  "request": [
    {
      "type": "INVOKE",
      "sender_address": "0x779ba6e4e227947acbbdfb978a292c401339027eeb3d768f5d12cd2e818265a",
      "calldata": [
        "0x1",
        "0x302d332e9aceb184e5f301cb62c85181e7fc3b30559935c5736e987de579f6e",
        "0xe654a0a9b2953a6fd9084842d9b9abc308341e6cd2ab57856441c542e51525",
        "0x26",
        "0x4b61126a7def0956cb4ff342ba72d850ea6b78b0ddb3e0b45f3a99bc9eb5995",
        "0x23",
        "0x779ba6e4e227947acbbdfb978a292c401339027eeb3d768f5d12cd2e818265a",
        "0x0",
        "0x15180",
        "0x0",
        "0x296e1a5ad28c9bf32b9570d6e1bedae77917866cd5d92aea4ef9271905ef549",
        "0x6",
        "0x1",
        "0x0",
        "0x1",
        "0x13bcbe7318fb8aa219d264dcf5916feb873e596389ba93d923f9a23378cb743",
        "0x1",
        "0x375b274b36284deef7364364c35708dac35c93a83e537b59ecc3712126fba5f",
        "0x3",
        "0x697066733a2f2f6261666b72656968746f657466676363636d346478703365",
        "0x7274687a66377168366f6d33656c716374366c3233686a6379617035687736",
        "0x66347834",
        "0x1",
        "0x13bcbe7318fb8aa219d264dcf5916feb873e596389ba93d923f9a23378cb743",
        "0x1",
        "0x375b274b36284deef7364364c35708dac35c93a83e537b59ecc3712126fba5f",
        "0x1",
        "0x3",
        "0x697066733a2f2f6261666b72656963667777327035716e776b333274777478",
        "0x3561766867636c7763356870716a6966376779367034707166743778336165",
        "0x74663779",
        "0x4",
        "0x2b63a8a92b7c67484ab99c4307c7db41b15b9a3c33359cd2b2459fd7f543a9c",
        "0x213bb25044b189ccfda9882999dba32e011781dc11b2a6efa2b3d232824378e",
        "0x47ee3743ce7ad0ffcdb1ba51c9730a77cafd0ca51539714e711258f86c9f8af",
        "0x53d98050a9738da0eac7498d909ea03f6eb03d07fb95877b54ff8acf7712276",
        "0x3",
        "0x697066733a2f2f6261666b726569636c66747536646e37666e646337367533",
        "0x703775696c6e767474656b68647a6f726c6571677a63713772616a7a333366",
        "0x376c3375",
        "0x0",
        "0x4044615dac19333d751a0f9393c6f9e047b0674347f3aba7a3fc0ae2d470"
      ],
      "version": "0x100000000000000000000000000000001",
      "signature": [
        "0x772d855e622d05fa39e2b1d05cd3936c259c1c128f362b1377970ab42b13458",
        "0xd1c76646542f3faf6796d703e6fc9a138b65c626a245d6802023dccc8cc3de"
      ],
      "nonce": "0x8",
      "max_fee": "0x0"
    }
  ],
  "block_id": "pending",
  "simulation_flags": [
    "SKIP_VALIDATE"
  ]
}
 
        41: Transaction execution error: {"execution_error":"Error in the called contract (0x0779ba6e4e227947acbbdfb978a292c401339027eeb3d768f5d12cd2e818265a):\nError at pc=0:15647:\nGot an exception while executing a hint: Custom Hint Error: Requested contract address ContractAddress(PatriciaKey(StarkFelt(\"0x0302d332e9aceb184e5f301cb62c85181e7fc3b30559935c5736e987de579f6e\"))) is not deployed.\nCairo traceback (most recent call last):\nUnknown location (pc=0:233)\nUnknown location (pc=0:5191)\nUnknown location (pc=0:11307)\n","transaction_index":0}
        ```

**Comment by bonustrack** [comment]
I was thinking of something like this:
image

Ideally on the first page we would see the combined tokens and NFTs for all the treasuries, and when we click on a specific treasury we see the button for WC, Copy and Send token/NFT

**Comment by Sekhmet** [comment]
@bonustrack can we handle design in the upcoming PR? This PR is already pretty big and ideally designs will be more concrete by then (like how exactly should screen for single treasury look like etc.)

**Comment by Sekhmet** [comment]
> Somehow I'm not able to create a Starknet Sepolia space, got this error on Argent X

Is your account deployed? `0x779ba6e4e227947acbbdfb978a292c401339027eeb3d768f5d12cd2e818265a` (sender address) is not on chain.

**Comment by bonustrack** [comment]
> @bonustrack can we handle design in the upcoming PR? This PR is already pretty big and ideally designs will be more concrete by then (like how exactly should screen for single treasury look like etc.)

Sure

**Comment by bonustrack** [comment]
I dont see the name of the treasury in the editor, (not like on your screenshot), was this removed? Also why there isn't the read only treasury as option in execution?
image

**Comment by Sekhmet** [comment]
> I dont see the name of the treasury in the editor, (not like on your screenshot), was this removed?

@bonustrack are you sure you are on latest branch and changes?

image


It definitely should show name and type:
https://github.com/snapshot-labs/sx-monorepo/blob/b72c0a8bcd867cdfa9f445dcb46b5cc4a41ef5c6/apps/ui/src/views/Editor.vue#L392-L398

> Also why there isn't the read only treasury as option in execution?

You can see my reasoning in the PR description, specifically this:
> We have two sources of truth for treasuries - executions and user configured treasuries on metadata, with this PR treasuries configured in metadata are used as a "whitelist" of executors that should be displayed on UI (in both treasury as well in proposal creation). You can also add treasuries that are not linked to executor to create read only treasury (can't be used in execution).

Read-only treasury doesn't have any execution strategy related to it, it can be just any address added to UI so we can't build the execution for proposal as we have no execution strategy for it.

**Comment by bonustrack** [comment]
Ok sorry I was on the wrong commit, I do see the treasury names now that's great. For the read only treasuries, I don't think it's an issue if there isn't any execution strategy related to it, it's no bidding so there might never been any execution strategy. But I understand it will add complexity and that something we can solve later.

**Comment by bonustrack** [comment]
Got this error when creating a space on SN Sepolia, with "No execution simple majority"
image

**Pull request merged**
