### PR TITLE
feat(ux): sort proposals results by weight

### PR DESCRIPTION
**Pull request by wa0x6e**
### Summary

Closes: #227

Sort proposals results by weight, ~~when type !== basic~~ for all voting type

Screenshot 2024-04-01 at 10 58 48

Screenshot 2024-04-01 at 12 26 47

### How to test

1. Go to http://localhost:8080/#/s:ens.eth/proposal/0x6ba81cd2997288cc49ae1b95921ec8f107e8ffb9733321d53d488e2b30710b86
2. It should show results in same order as https://snapshot.org/#/ens.eth/proposal/0x6ba81cd2997288cc49ae1b95921ec8f107e8ffb9733321d53d488e2b30710b86
3. Go to http://localhost:8080/#/s:test.wa0x6e.eth/proposal/0x46a984c60c16af8214d8a50dc964cdabfbb39fd57a5d1f9ad5ff62dca4e2f856
4. It should show results in for, against, abstain order

### CODE REVIEW

**Comment by bonustrack** [comment]
We should sort results even if type is basic. Havent tested but on your 2nd screenshot 1 icon is missing and icons are on wrong choice

**Comment by wa0x6e** [comment]
> We should sort results even if type is basic. Havent tested but on your 2nd screenshot 1 icon is missing and icons are on wrong choice

Fixed

**Comment by bonustrack** [comment]
Border color is missing or wrong

Screenshot_20240401_154843_Chrome

**Comment by wa0x6e** [comment]
fixed

**Review by bonustrack — APPROVED** [review]
tACK

**Pull request merged**
