### PR TITLE
feat: add flash message introducing v2

### PR DESCRIPTION
**Pull request by wa0x6e**
### Summary

Closes: https://github.com/snapshot-labs/workflow/issues/318

This PR adds a new flash message on the bottom right corner, introducing the v2, as well as show link to go back to v1

Once closed, flash message will not appear again (state saved in localStorage)

Screenshot 2024-12-10 at 00 12 23

### How to test

1. Open the app (not available on landing page)
2. Close the message
3. Message will not appear again on page refresh

### CODE REVIEW

**Comment by wa0x6e** [comment]
Requesting @ChaituVR for code check, still waiting for @bonustrack for UI validation

**Review by ChaituVR — COMMENTED** [review]
tAck for code, lets wait for approval from @bonustrack 


seems bit off here 🤔 maybe because of the font?
image
or should be centered with padding-left 10px?
image

Not a design expert 🙈 can ignore this comment

**Comment by wa0x6e** [comment]
@bonustrack Any more improvement left to add ? Else we should release this feat asap, as the more we wait, the less useful it will be

**Comment by bonustrack** [comment]
Design looks good, I just noticed the link to v1 doesn't work for me

image

Also the popup should appear even on the landing page.

**Comment by bonustrack** [comment]
I'm merging this for now, we can fix the issue with v1 link in another PR.

**Pull request merged**
