### PR TITLE
feat: add EthRelayer execution support on L2

### PR DESCRIPTION
**Pull request by Sekhmet**
### Summary

This PR adds EthRelayer support. Only part missing is performing execution on L1 which depends on some contract-level changes that we need to wait for.

Depends on: https://github.com/snapshot-labs/sx-monorepo/pull/321

### How to test

1. Run local services (`yarn dev:full`).
2. Create space with EthRelayer execution strategy. Add some Safe address as avatar (it has to have some funds in it). Give it some short max voting delay.
3. Create proposal with execution.
4. Vote on it.
5. Wait for proposal to end.
6. Execute button should show up (it might fail for some time due to timestamps being not accurate initially, will need to look into it).
7. Click on it, execution on L2 should be triggered.

### To-Do

- [x] Add missing fields to Subgraph APIs.
- [x] Add `executors_destinations` to metadata as source for API.
- [x] Add Starknet execution through mana (currently done on UI).
- [ ] Finish execution on L1 (future PR).

### CODE REVIEW

**Comment by bonustrack** [comment]
Indexing on SN Sepolia is stuck in a loop for me at block 42326 with this error:

```sh
api:dev: [1714428010489] INFO: handling block
api:dev:     component: "checkpoint"
api:dev:     blockNumber: 42326
api:dev: [1714428010495] INFO: found contract event
api:dev:     component: "checkpoint"
api:dev:     contract: "0x6173069dd27ca75b424d51cc5d39da6612a55b7457d96c388490d14af50ca36"
api:dev:     event: "MetadataUriUpdated"
api:dev:     handlerFn: "handleMetadataUriUpdated"
api:dev: failed to update space metadata TypeError: Cannot read properties of undefined (reading '0')
api:dev:     at handleSpaceMetadata (/Users/less/WebstormProjects/snapshot-labs/sx-monorepo/apps/api/src/ipfs.ts:72:73)
api:dev:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
api:dev:     at async Object.handleMetadataUriUpdated (/Users/less/WebstormProjects/snapshot-labs/sx-monorepo/apps/api/src/writer.ts:104:5)
api:dev:     at async StarknetProvider.handleTx (/Users/less/WebstormProjects/snapshot-labs/sx-monorepo/node_modules/@snapshot-labs/checkpoint/dist/src/providers/starknet/index.js:170:29)
api:dev:     at async StarknetProvider.handleBlock (/Users/less/WebstormProjects/snapshot-labs/sx-monorepo/node_modules/@snapshot-labs/checkpoint/dist/src/providers/starknet/index.js:84:13)
api:dev:     at async StarknetProvider.processBlock (/Users/less/WebstormProjects/snapshot-labs/sx-monorepo/node_modules/@snapshot-labs/checkpoint/dist/src/providers/starknet/index.js:53:9)
api:dev:     at async Checkpoint.next (/Users/less/WebstormProjects/snapshot-labs/sx-monorepo/node_modules/@snapshot-labs/checkpoint/dist/src/checkpoint.js:314:31)
api:dev:     at async Checkpoint.start (/Users/less/WebstormProjects/snapshot-labs/sx-monorepo/node_modules/@snapshot-labs/checkpoint/dist/src/checkpoint.js:162:16)
api:dev: [1714428010799] ERROR: error occurred during block processing
api:dev:     component: "checkpoint"
api:dev:     blockNumber: 42326
api:dev:     err: {
api:dev:       "type": "Error",
api:dev:       "message": "d",
api:dev:       "stack":
api:dev:           Error: d
api:dev:               at Object.handleMetadataUriUpdated (/Users/less/WebstormProjects/snapshot-labs/sx-monorepo/apps/api/src/writer.ts:114:11)
api:dev:               at processTicksAndRejections (node:internal/process/task_queues:95:5)
api:dev:               at async StarknetProvider.handleTx (/Users/less/WebstormProjects/snapshot-labs/sx-monorepo/node_modules/@snapshot-labs/checkpoint/dist/src/providers/starknet/index.js:170:29)
api:dev:               at async StarknetProvider.handleBlock (/Users/less/WebstormProjects/snapshot-labs/sx-monorepo/node_modules/@snapshot-labs/checkpoint/dist/src/providers/starknet/index.js:84:13)
api:dev:               at async StarknetProvider.processBlock (/Users/less/WebstormProjects/snapshot-labs/sx-monorepo/node_modules/@snapshot-labs/checkpoint/dist/src/providers/starknet/index.js:53:9)
api:dev:               at async Checkpoint.next (/Users/less/WebstormProjects/snapshot-labs/sx-monorepo/node_modules/@snapshot-labs/checkpoint/dist/src/checkpoint.js:314:31)
api:dev:               at async Checkpoint.start (/Users/less/WebstormProjects/snapshot-labs/sx-monorepo/node_modules/@snapshot-labs/checkpoint/dist/src/checkpoint.js:162:16)
api:dev:     }
mana:dev: processing 0 transactions
api:dev: Handle space metadata uri updated
api:dev: failed to update space metadata TypeError: Cannot read properties of undefined (reading '0')
api:dev:     at handleSpaceMetadata (/Users/less/WebstormProjects/snapshot-labs/sx-monorepo/apps/api/src/ipfs.ts:72:73)
api:dev:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
api:dev:     at async Object.handleMetadataUriUpdated (/Users/less/WebstormProjects/snapshot-labs/sx-monorepo/apps/api/src/writer.ts:104:5)
api:dev:     at async StarknetProvider.handleTx (/Users/less/WebstormProjects/snapshot-labs/sx-monorepo/node_modules/@snapshot-labs/checkpoint/dist/src/providers/starknet/index.js:170:29)
api:dev:     at async StarknetProvider.handleBlock (/Users/less/WebstormProjects/snapshot-labs/sx-monorepo/node_modules/@snapshot-labs/checkpoint/dist/src/providers/starknet/index.js:84:13)
api:dev:     at async StarknetProvider.processBlock (/Users/less/WebstormProjects/snapshot-labs/sx-monorepo/node_modules/@snapshot-labs/checkpoint/dist/src/providers/starknet/index.js:53:9)
api:dev:     at async Checkpoint.next (/Users/less/WebstormProjects/snapshot-labs/sx-monorepo/node_modules/@snapshot-labs/checkpoint/dist/src/checkpoint.js:314:31)
api:dev:     at async Checkpoint.start (/Users/less/WebstormProjects/snapshot-labs/sx-monorepo/node_modules/@snapshot-labs/checkpoint/dist/src/checkpoint.js:162:16)
```

Also I've noticed that we don't enforce network on L1 relayer execution deployment, we should enforce it.

**Comment by bonustrack** [comment]
If I ignore the space update error I'm able to create a proposal with execution and vote on it. When I try to trigger the execution I got this error from Mana:

image

Also shouldn't we allow execution if min duration pass? And should we hide "Execute queued transactions" if step 1 is not done?

Anyhow feel free to merge this PR if you prefer, changes can be done in others PR.

**Comment by Sekhmet** [comment]
Updated all those issues, we need to depend on PR that can hardcode fees.

**Comment by bonustrack** [comment]
Can we merge this PR?

**Comment by bonustrack** [comment]
I tried to create a space on Sepolia but the API fail to index it with this error:
image
In production API it was indexed:
https://testnet.snapshotx.xyz/#/sn-sep:0x015cce180cfd6d588f1e7b8dc53108556d8e871400294d0cf6382e77b0553818
https://testnet.snapshotx.xyz/#/sn-sep:0x032a78bef96dc33803cb30396b7ba329f0d98043817a19e2f996e844b68d3001 (2nd space created)

**Comment by Sekhmet** [comment]
I couldn't reproduce this issue now, just created new space and it worked: `0x64a62d57089db99a374316130a2db365856e0e26a26b524464d6b24e287f7a8`

Maybe some temporary issue? But it looks like either pineapple returned wrong data or returned some error (but the response is huge because it found invalid character at 44k character).

**Comment by bonustrack** [comment]
I have now another error that shutdown sx-api
image
It seem related to the RPC API

**Comment by Sekhmet** [comment]
@bonustrack that's the issue I reported to Infura, if you end up rate limited they concat valid response and error response together so you get invalid payload. It's unrelated to this PR, if it crashes checkpoint it should be reported in checkpoint repo.

**Comment by bonustrack** [comment]
- We should enforce correct network for L1 Safe module deployment, currently it trigger with mainnet for a Sepolia space.
- Somehow when I trigger "Execute proposal" fail with this error "Before max end timestamp" while proposal ended, see tx:
https://sepolia.starkscan.co/tx/0x1ae666f8180d2552952c7bb074f01e0703d64472671502a0cc5e9d26d8f129a
Here is my space proposal: http://localhost:8080/#/sn-sep:0x02d0863c994f70ee3ddcf1530a6281e030f28e95dd52e29bec795238aff4d17f/proposal/1

**Comment by bonustrack** [comment]
"Execute proposal" finally worked after some time

**Comment by Sekhmet** [comment]
> Somehow when I trigger "Execute proposal" fail with this error "Before max end timestamp" while proposal ended

Yes, I mentioned it in the PR, we probably need to add some margin to handle it, but it will add some delay (10 minutes should be safe).

**Comment by bonustrack** [comment]
What's the reason for that delay again?

**Comment by Sekhmet** [comment]
I think it's because we have to wait for block to be created, so if we have last block at 13:50, proposal ending at 13:51 then we have to wait for block at 13:55 to be able to execute it.

**Comment by Sekhmet** [comment]
We got L1 execution (executed via UI with temporary action just for testing purposes): https://sepolia.etherscan.io/tx/0x1519c4690d8422f9d89287cd9e72ebffb8131e23207cfa14c00b4680cffeaf82

Missing features:
- Better handle max end timestamp (but this is actually more global issues that will also affect min-end for strategies that support it): https://github.com/snapshot-labs/sx-monorepo/issues/351
- Show final execution status (pending contract updates).
- Properly handle transactions (currently L1 execution transaction gets added to transactions as Starknet transaction), but can be worked on when we have contracts ready and finalise the flow.

**Comment by bonustrack** [comment]
Can we fix this and merge this PR?

> We should enforce correct network for L1 Safe module deployment, currently it trigger with mainnet for a Sepolia space.

**Comment by Sekhmet** [comment]
Sure, forgot about this point.

**Review by bonustrack — APPROVED** [review]

**Pull request merged**
