### PR TITLE
fix: update favicon

### PR DESCRIPTION
**Pull request by wa0x6e**
### Summary

Related to https://discord.com/channels/955773041898573854/1030773050217615440/1282255908466069545

Update favicon to use the zap logo

### How to test

1. Go to http://localhost:8080/
2. It should show the zap logo as favicon on all pages (excluding spaces page)

### CODE REVIEW

**Review by ChaituVR — APPROVED** [review]
tAck

**Comment by bonustrack** [comment]
Check new favicon in `sx-ui` channel

**Comment by wa0x6e** [comment]
> Check new favicon in `sx-ui` channel

updated

**Review by bonustrack — APPROVED** [review]
tACK

**Pull request merged**
