### PR TITLE
feat: create oSnap execution in Editor

### PR DESCRIPTION
**Pull request by Sekhmet**
### Summary

This PR makes it possible to create oSnap execution on offchain spaces.

Features as of now:
- added conversion for transactions from internal to oSnap format and inject it into proposal payload
- use real values in the payload (spread across different commits to make reviewing easier, module address, chainId, treasuryName)
- lock `Basic voting` when oSnap proposal is created.

Missing:
- allow two treasuries to be used in single proposal (https://github.com/snapshot-labs/sx-monorepo/issues/138).

Towards https://github.com/snapshot-labs/sx-monorepo/issues/467

### How to test

1. Enable oSnap on your treasuries on your space on testnet.snapshot.org (https://docs.uma.xyz/developers/osnap/osnap-deployment-tutorial)
2. You can create proposal on SX on that space and build your execution.
3. Execution is visible on both v1 and SX.

### Screenshots

image

### CODE REVIEW

**Comment by ChaituVR** [comment]
@Sekhmet conflicts

**Comment by bonustrack** [comment]
I've noticed this issue in the token modal, the asset list don't take the whole width:
image

Otherwise it's working well for me

**Comment by bonustrack** [comment]
@Sekhmet Forgot to say but the issue of full width also happen on the contact select modal

**Review by bonustrack — APPROVED** [review]
tACK

**Pull request merged**
