### PR TITLE
feat: integrate Axiom

### PR DESCRIPTION
**Pull request by Sekhmet**
### Summary

Closes: https://github.com/snapshot-labs/sx-monorepo/issues/156
Staging branch on: https://github.com/snapshot-labs/sx-monorepo/pull/4

This PR adds support for Axiom execution strategy (this one is mock from Axiom team).

When creating space you can now add Axiom execution strategy. With it enabled votes will be broadcast to highlight instance and later proven by Axiom.

Once voting window ends you can generate proofs from UI and execute transaction as-if votes were on-chain.

### Test plan

- Run `yarn dev:full`, you can change sepolia network's start index.
- Mint & delegate to yourself this token https://sepolia.etherscan.io/address/0x6fd821e79cdf212ad8b06c59b28fe8c2185291d4#writeContract
- Create space on Sepolia with ERC-20 Comp tokens voting/proposition power strategies using this contract `0x6fd821e79cdf212ad8b06c59b28fe8c2185291d4`.
- Use Axiom execution strategy (contract `0x6fd821e79cdf212ad8b06c59b28fe8c2185291d4`, slotIndex `8`).
- Change max voting delay to something shorter (10 minutes).
- After space is deployed go to settings and copy execution address, add it as treasury.
- Send some ERC20 token to this treasury to use as execution.
- Create proposal **with axiom execution** and vote on it.
- Once voting period has ended you should see `Finalize proposal` button, click on it and wait some time (5-10 minutes).
- Refresh page, it should show `Execute proposal` eventually, click this button.
- Wait some time, refresh page, it should show link to proposal execution.

Alternatively use this space instead of creating your own: http://localhost:8080/#/sep:0x648b2C6710f92d59E2562a61E9bdF2Cbe8f87186

### CODE REVIEW

**Comment by bonustrack** [comment]
I've tried to create a proposal on your space here: http://localhost:8080/#/sep:0x648b2C6710f92d59E2562a61E9bdF2Cbe8f87186/proposal/5

When I click to finalize the proposal, it fail on Mana with this error:
```json
{
    "jsonrpc": "2.0",
    "error": {
        "code": 500,
        "message": "unauthorized",
        "data": {
            "message": "request to http://ec2-44-197-171-215.compute-1.amazonaws.com:8000/query failed, reason: socket hang up",
            "type": "system",
            "errno": "ECONNRESET",
            "code": "ECONNRESET"
        }
    },
    "id": null
}
```

I see also this error in logs:
```sh
mana:dev: error LibraryError: RPC: starknet_estimateFee with params {"request":[{"type":"INVOKE","sender_address":"0x4d1815453874b0b0ddebff592485f151b9886dee32afd404846c318f54fb161","calldata":["0x1","0x1f8544918b5d9b4833fb2ba2d0c7ceb0d699ae7f2b8b23ea129c9a10fe8046c","0x232e20d533377ce3b5e4db31ecfaa561eb2b2f29af46dcc0eca9460eb4f89a3","0x16","0x65bba377","0x20","0x3","0x1","0x3a4129f0acec7dced75cbde55aae3c0f4da9fce26fa8cf93e722da56c3cf20c","0x3","0x2","0x65bba38c","0x0","0x1","0x65bba374","0x1","0x65bba374","0x0","0x1","0x65bba38c","0x1","0x65bba374","0x0","0x1","0x65bba38c","0x1"],"version":"0x100000000000000000000000000000001","signature":["0x71668b77650967b85c4f3893c9cc0005a33206bccf8409189f32038e9f293e8","0xfc331184e30cac69a132944240bf8c22c844d9120899d55eca95a5bab55dc3"],"nonce":"0x87","max_fee":"0x0"}],"block_id":"pending"}
mana:dev:  40: Contract error: {"revert_error":"Execution error at transaction index 0: Error in the called contract (0x04d1815453874b0b0ddebff592485f151b9886dee32afd404846c318f54fb161):\nError at pc=0:15647:\nGot an exception while executing a hint: Requested contract address ContractAddress(PatriciaKey(StarkFelt(\"0x01f8544918b5d9b4833fb2ba2d0c7ceb0d699ae7f2b8b23ea129c9a10fe8046c\"))) is not deployed.\nCairo traceback (most recent call last):\nUnknown location (pc=0:233)\nUnknown location (pc=0:5191)\nUnknown location (pc=0:11307)\n"}
mana:dev:     at RpcProvider.errorHandler (/Users/less/WebstormProjects/snapshot-labs/sx-monorepo/node_modules/starknet/src/provider/rpc.ts:123:13)
mana:dev:     at RpcProvider.fetchEndpoint (/Users/less/WebstormProjects/snapshot-labs/sx-monorepo/node_modules/starknet/src/provider/rpc.ts:142:12)
mana:dev:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
mana:dev:     at async Account.estimateInvokeFee (/Users/less/WebstormProjects/snapshot-labs/sx-monorepo/node_modules/starknet/src/account/default.ts:141:22)
mana:dev:     at async HerodotusController.cacheTimestamp (/Users/less/WebstormProjects/snapshot-labs/sx-monorepo/packages/sx.js/dist.cjs/clients/starknet/herodotus/index.js:27:21)
mana:dev:     at async processProposal (/Users/less/WebstormProjects/snapshot-labs/sx-monorepo/apps/mana/src/stark/herodotus.ts:193:21)
mana:dev:     at async registeredProposalsLoop (/Users/less/WebstormProjects/snapshot-labs/sx-monorepo/apps/mana/src/stark/registered.ts:85:9)
```

**Comment by Sekhmet** [comment]
Does it happen all the time? Looks like API/network issue and it's most likely temporary.

Second error is usually there if you interact with Starknet spaces and are on wrong network, but that would be unrelated there as this touches only EVM spaces.

**Comment by bonustrack** [comment]
Yes it happen all the time tried maybe 10 times, and for the second error I haven't interacted with Starknet space, it might come from earlier test

**Comment by Sekhmet** [comment]
I could reproduce it now, looks like issue with Axiom API, I reported it to them.

**Comment by Sekhmet** [comment]
@bonustrack should work, Axiom team said it could have been related to Alchemy being down.

I tested on my proposal via `curl` and on your proposal via UI and it now worked (but you will need to create second proposal to test with now).

**Review by bonustrack — COMMENTED** [review]
tACK works well now, I was able to run the whole flow

**Review by bonustrack — APPROVED** [review]

**Comment by Sekhmet** [comment]
Deployed subgraphs, will merge once fully synced so deployment is not broken.

**Pull request merged**
