### PR TITLE
fix: fix invalid query selector

### PR DESCRIPTION
**Pull request by wa0x6e**
### Summary

Closes: #845 

This PR fixes the console error, and apply the correct behavior to the intercom launcher button.

- The button should be hidden via CSS on small screen
- Remove the initializing skipping on small screen, so that the button shows when initialized on small screen, and resized to bigger screen later

### CODE REVIEW

**Comment by bonustrack** [comment]
I'm still seeing the error in console
image

**Review by ChaituVR — APPROVED** [review]
tAck

**Review by bonustrack — APPROVED** [review]
tACK

**Comment by wa0x6e** [comment]
Wait, this not working yet

**Comment by wa0x6e** [comment]
Fixed, description updated to reflect what this PR is fixing

**Pull request merged**
