### PR TITLE
chore: update axiom strategy address

### PR DESCRIPTION
**Pull request by Sekhmet**
### Summary

Closes: https://github.com/snapshot-labs/sx-monorepo/issues/186

### CODE REVIEW

**Comment by bonustrack** [comment]
We should also change the ABI in the subgraph

**Comment by bonustrack** [comment]
You can take it from Etherscan

**Comment by Sekhmet** [comment]
@bonustrack I didn't see any changes in the ABI, however I see that it was deployed with querySchema of `A09CC16CCAA32B96CA5C404C1B4BE60D7883A7178F432E8F9F3C22157FC0F873` that I can't decode (`parseBytes32String` doesn't work on this), before it was `3000000000000000000000000000000000000000000000000000000000000000` - decoding into `0`.

So I'm not sure what it should be in https://github.com/snapshot-labs/sx-monorepo/pull/4 without further docs.

**Comment by Sekhmet** [comment]
Merging so we can index updated axiom strategies on prod server - I have issues running local node due to rate limits.

**Pull request merged**
