### PR TITLE
refactor: get app name from useApp composable

### PR DESCRIPTION
**Pull request by wa0x6e**
### Summary

Working toward https://github.com/snapshot-labs/workflow/issues/142

This PR refactors the UI to pull the `APP_NAME` from a single source (constants, then `useApp` composable).

Using the composable instead of the constant directly will allow changing the app name after initialization (e.g. for white label)

### Note 

There's still a last part, walletLink, which is getting its name directly from the constant. Making it dynamic will requires some more refactoring out-of-scope for this PR

### CODE REVIEW

**Review by ChaituVR — APPROVED** [review]
utAck, but do we really need to change "Snapshot" on walletconnect and everywhere? It is still snapshot under the hood 😅  don't think we do this on snapshot.org

**Comment by wa0x6e** [comment]
On white label, I am planning to replace app name by the dao name

**Comment by Sekhmet** [comment]
I think that it might make sense to keep Snapshot name for connectors (Coinbase already uses static APP_NAME, I assume that whitelabeled name would be updated at composable level).

What do you think @bonustrack

**Comment by bonustrack** [comment]
Yes I would keep Snapshot name for connectors

**Comment by wa0x6e** [comment]
> Yes I would keep Snapshot name for connectors

So on whitelabel, when you connect with a wallet, it will says "Connect to Snapshot" ?

**Comment by wa0x6e** [comment]
App name on wallet connectors reverted to always use default APP_NAME

**Review by Sekhmet — APPROVED** [review]
tACK

**Pull request merged**
