### PR TITLE
chore: editor improvements

### PR DESCRIPTION
**Pull request by bonustrack**
Various improvements in the editors:

- Support deleting a choice using backspace key
- Add placeholder to content body
- Add tooltip for drafts button
- Separate draft and publish button, and use primary color for publish
- Rename voting type to voting system

### CODE REVIEW

**Comment by wa0x6e** [comment]
> Support deleting a choice using backspace key

Let's say I have 3 choices: a, b, c

When I go to choice b, and delete the `b` character, the choice field is empty (current behavior)

When I BACKSPACE one more time, it's supposed to delete the empty choice, and I should end up with only 2 choices: a and c

But it's not the current behavior, deleting the choice 2 will also delete one character from the previous choice, so we end up with

choice 1: empty field
choice 2: c

**Comment by wa0x6e** [comment]
Button text is not aligned

Screenshot 2024-09-14 at 22 51 14

**Comment by wa0x6e** [comment]
Fixed the text vertical alignement

Screenshot 2024-09-14 at 23 01 07

Also fixed the button not being rounded on small screen

Screenshot 2024-09-14 at 23 01 11

**Comment by bonustrack** [comment]
> > Support deleting a choice using backspace key
> 
> Let's say I have 3 choices: a, b, c
> 
> When I go to choice b, and delete the `b` character, the choice field is empty (current behavior)
> 
> When I BACKSPACE one more time, it's supposed to delete the empty choice, and I should end up with only 2 choices: a and c
> 
> But it's not the current behavior, deleting the choice 2 will also delete one character from the previous choice, so we end up with
> 
> choice 1: empty field choice 2: c

Good catch, need to fix this

**Comment by wa0x6e** [comment]
I also added some improvement on the layout, forcing all content on same line, and truncating when needed

Before
Screenshot 2024-09-14 at 23 11 07

After
Screenshot 2024-09-14 at 23 11 15

**Review by wa0x6e — CHANGES_REQUESTED** [review]
See https://github.com/snapshot-labs/sx-monorepo/pull/761#issuecomment-2350997285

**Review by wa0x6e — APPROVED** [review]
tAck

**Pull request merged**
