### PR TITLE
fix: Editor title should reflect update status

### PR DESCRIPTION
**Pull request by wa0x6e**
### Summary

Toward #801

This PR shows the correct title in TopNav when editing a proposal

### How to test

1. Go to a proposal edition page
2. The tiltle in topnav should now says "Update proposal"

### CODE REVIEW

**Comment by ChaituVR** [comment]
How to go to a proposal edition page? is there an example URL?

**Comment by wa0x6e** [comment]
>

**Comment by wa0x6e** [comment]
> How to go to a proposal edition page? is there an example URL?

Create a pending onchain proposal, then edit it in the dropdown menu in the proposal overview page (same menu as delete)

**Comment by ChaituVR** [comment]
> Create a pending onchain proposal, then edit it in the dropdown menu in the proposal overview page (same menu as delete)

Ah, I was checking on offchain pending proposals. there is no option there weirdly 🤔

**Review by ChaituVR — APPROVED** [review]
tAck

**Pull request merged**
