### PR TITLE
fix: Delegators col width

### PR DESCRIPTION
**Pull request by ChaituVR**
### Summary
- Witdh of delegators is causing text to truncate
Untitled 4

### How to test

1. Go to http://localhost:8080/#/s:balancer.eth/delegates
2. click on delegators column header to sort
3. Notice that text of header is truncated before the fix

| Before | After |
| --- | --- |
| Untitled 4 | Untitled 5 |

### CODE REVIEW

**Comment by wa0x6e** [comment]
Issue still remain when the voting power symbol is long enough, better fix would be to truncate this column

**Comment by wa0x6e** [comment]
The not-working truncation is also forcing an horizontal scroll on small screen, and un-syncing the column width with the header

Screenshot 2024-09-14 at 23 28 19

**Review by wa0x6e — COMMENTED** [review]
See comments

**Comment by wa0x6e** [comment]
Also see https://snapshot.box/#/s:test.wa0x6e.eth/proposal/0x1ca55447da176052e43c80f151726b1d352e8bc10507bde803b0ee111e63aa1f/votes

**Comment by ChaituVR** [comment]
The main issue I want to fix is the col width of the header. when we sort, an arrow is added to it, and the text get truncated because of the smaller width
Before clicking 
Untitled 4
After clicking
image


Maybe we should handle truncation in separate issue?

**Comment by wa0x6e** [comment]
> The main issue I want to fix is the col width of the header. when we sort, an arrow is added to it, and the text get truncated because of the smaller width Before clicking Untitled 4 After clicking image
> 
> Maybe we should handle truncation in separate issue?

I see, I though you were talking about the content

**Review by wa0x6e — APPROVED** [review]

**Pull request merged**
