### PR TITLE
feat: display oSnap execution info

### PR DESCRIPTION
**Pull request by Sekhmet**
### Summary

This PR adds message about oSnap execution progress.

Because oSnap executions are per-treasury (and not per-proposal) design had to be updated to move execution status and actions into per-treasury sections.

Closes: https://github.com/snapshot-labs/sx-monorepo/issues/467

### How to test

1. Check proposals at different stages:
2. Waiting to be confirmed: http://localhost:8080/#/s:0cf5e.eth/proposal/0x0a04e2d340fcd5cfcac5d89369d152c8c9fefc59126c48b650785c147dc3d6aa
3. Executed: http://localhost:8080/#/s:0cf5e.eth/proposal/0x2a0752ef99d948dc753fb4b5359fe34a352aaf3c9f10b8ee5edf9ad4cde9246c
4. (CHECK COMMENT BELOW) Non compliant: http://localhost:8080/#/s:fabien.eth/proposal/0xeebb4a2cb25a84de837135b9be63246b1f78c1b351edc63a00652de0e419a4f3

Currently `osnap.uma.xyz` rejects requests from outside snapshot.org due to its CORS configuration. That means that checking for compliance will fail at the moment until it's addressed on their side (and message of `Execution details failed to load.` will be displayed). You can mock it during testing using this patch:
```diff
diff --git a/apps/ui/src/composables/useExecutionActions.ts b/apps/ui/src/composables/useExecutionActions.ts
index 486644a0..f7fd2225 100644
--- a/apps/ui/src/composables/useExecutionActions.ts
+++ b/apps/ui/src/composables/useExecutionActions.ts
@@ -142,14 +142,15 @@ export function useExecutionActions(
       });
 
       if (!data) {
-        const configCompliant = await isConfigCompliant(
-          execution.safeAddress,
-          execution.chainId
-        );
-
-        message.value = configCompliant.automaticExecution
-          ? 'Waiting for execution to be initiated.'
-          : 'Space is not configured for automatic execution.';
+        message.value = 'Space is not configured for automatic execution.';
+        // const configCompliant = await isConfigCompliant(
+        //   execution.safeAddress,
+        //   execution.chainId
+        // );
+
+        // message.value = configCompliant.automaticExecution
+        //   ? 'Waiting for execution to be initiated.'
+        //   : 'Space is not configured for automatic execution.';
       } else if (data.executionTransactionHash) {
         try {
           executionNetwork.value = getNetwork(execution.networkId);

```

### Screenshots

Space is misconfigured for automatic execution:
image

Proposal automatic execution was initiated:
image

Proposal has been executed:
image

### CODE REVIEW

**Review by bonustrack — APPROVED** [review]
tACK

**Comment by Sekhmet** [comment]
@bonustrack do you want to merge this PR with config compliance check removed (due to osnap.uma.xyz CORS issue) or do we want to wait until this is resolved?

**Comment by bonustrack** [comment]
Can't we merge this and keep compliance check error message? If it get resolved would it require further change here?

**Comment by Sekhmet** [comment]
We can keep it like this, once resolved it should just work automatically.

**Pull request merged**
