### PR TITLE
feat: add voted icon next to proposal title in proposal lists

### PR DESCRIPTION
**Pull request by wa0x6e**
### Summary

Closes: #230

### How to test

1. Go to a space where you have voted for some proposals
2. In the proposals list, a green checkmark icon should appear next to proposal you have voted for

Screenshot 2024-04-04 at 23 51 26

Long proposal title should truncate

Screenshot 2024-04-05 at 00 45 02

On small screen

Screenshot 2024-04-05 at 00 45 14

### CODE REVIEW

**Comment by bonustrack** [comment]
It's broken on small screen
image

**Comment by wa0x6e** [comment]
I see `md:truncate md:text-ellipsis` class on the title.

Does it means that we truncate only on medium screen and larger, and allow multiline on small screen ? Or is it supposed to be the opposite ?

**Comment by bonustrack** [comment]
> Does it means that we truncate only on medium screen and larger, and allow multiline on small screen ?
Yes that's the idea

**Comment by wa0x6e** [comment]
fixed

**Comment by bonustrack** [comment]
Nothing changed for me

**Review by bonustrack — APPROVED** [review]
tACK

**Pull request merged**
