### PR TITLE
feat: format addresses to common format across app

### PR DESCRIPTION
**Pull request by Sekhmet**
### Summary

Ethereum checksummed addresses and Starknet padded addresses will be used across app.

Closes: https://github.com/snapshot-labs/sx-monorepo/issues/67

Not sure if I caught all cases - if there are places where we do not shorten addresses it won't be updated, but I don't recall such places.

### How to test

1. Check across apps, there are no non-checksummed or non-padded addresses.

### CODE REVIEW

**Comment by bonustrack** [comment]
Something wrong, I should see same avatar and my .stark domain in topnav logger but currently it doesnt
image

**Comment by bonustrack** [comment]
The avatar looks good but I still not see my stark domain somehow

**Comment by bonustrack** [comment]
Works on topnav now, I just realized it doesn't work here: http://localhost:8080/#/sn:0x05702362b68a350c1cae8f2a529d74fdbb502369ddcebfadac7e91da37636947/proposal/4/votes
First vote should be less.stark. On the vote page we use Stamp API, it works for ENS domains, any idea whats wrong?

**Comment by bonustrack** [comment]
Ok I can see it works now with another domain:
https://bafybeigf73pvn2mrdcedcq2gaq6lwxiggwlwdj5gcidra6oa43w2qpiq2m.on.fleek.co/#/sn:0x05702362b68a350c1cae8f2a529d74fdbb502369ddcebfadac7e91da37636947/proposal/6/votes

**Review by bonustrack — APPROVED** [review]
tACK, I think actually the SX API should have the same address format too, it will make it easier for integrators if we have same format everywhere, it will also slightly reduce complexity in our UI, but can be done in another PR.

**Comment by Sekhmet** [comment]
sx-api should already be using formatted addresses, it wasn't handled on voters though (as here we only unwrapped variants, without formatting). Updated this as well.

**Pull request merged**
