### PR TITLE
fix(ux): make all sticky nav horizontally scrollable

### PR DESCRIPTION
**Pull request by wa0x6e**
### Summary

On narrow screen, the proposal top nav is preventing the content from resizing correctly

Before fix

Screenshot 2024-08-31 at 01 32 07

After fix

Screenshot 2024-09-04 at 13 09 49

This PR will:

- make the proposal page top sticky navigation horizontally scrollable, like all other top sticky nav
- fix all sticky nav to have the same style (same gradient and with buttons, like the space settings nav)

### How to test

1. Visit any pages with sticky nav (proposal, space user, treasuries, etc ...)
2. Resize the screen, and decrease width
3. The sticky nav should be horizontally scrollable on narrow screen, but buttons and gradient

### CODE REVIEW

**Comment by ChaituVR** [comment]
I am not able to reproduce this weirdly 🤔

**Comment by wa0x6e** [comment]
Description updated

**Comment by bonustrack** [comment]
Doesn't work fully for me, right side missing white background and border
image

**Comment by ChaituVR** [comment]
Instead of handling things seperately on everything, I think we should keep 320px as the minimum width of the app, then even if someone resize below that everything will be scrollable.

https://www.reddit.com/r/web_design/comments/3s5hnp/whats_the_smallest_cell_phone_width_for/

**Comment by wa0x6e** [comment]
Fixed, all sticky nav also have same styling (same buttons and gradient) for better consistency

**Comment by wa0x6e** [comment]
I've fixed the merge conflicts, you can merge once confirmed

**Pull request merged**
