### PR TITLE
fix: Improve topic component styles

### PR DESCRIPTION
**Pull request by ChaituVR**
### Summary

- Remove border-bottom for reply button
- Add more space between content and like, comment icons

### How to test

1. Go to any discussion page http://localhost:8080/#/s:safe.eth/proposal/0x2c2ad686e94fd97903de8ee520b90d400c98a1985e31b21416da095b28373f18/discussion
2. Check for new changes

### CODE REVIEW

**Comment by wa0x6e** [comment]
Screenshot 2024-09-04 at 13 36 04

`px-4` is applied twice

**Comment by bonustrack** [comment]
Topic content width is still different than the proposal content width. Also view discussion button is not aligned
image

**Comment by ChaituVR** [comment]
As suggested on discord we now have border width same as reply width
image

**Review by bonustrack — APPROVED** [review]
tACK

**Pull request merged**
