### PR TITLE
refactor: remove gor and sn-tn networks

### PR DESCRIPTION
**Pull request by Sekhmet**
### Summary

This PR removes `gor` and `sn-tn` networks as Goerli got deprecated.

Closes: https://github.com/snapshot-labs/sx-monorepo/issues/324

### How to test

1. Everything should keep working.

### CODE REVIEW

**Comment by wa0x6e** [comment]
Waiting for thegraph index fix, to test space creation

**Comment by Sekhmet** [comment]
> Waiting for thegraph index fix, to test space creation

Is it still broken? It should work.

**Comment by wa0x6e** [comment]
Was able to create eth sepolia as usual, but hit an error for starknet sepolia

Screenshot 2024-05-10 at 17 53 31
Screenshot 2024-05-10 at 17 53 41

**Comment by Sekhmet** [comment]
@wa0x6e have you use Whitelist voting strategy there?
Only thing I could see causing it is if you used whitelist strategy with invalid format (it needs to be `address:VP` in each line).

I tried reproducing otherwise and had no issues - probably should add some kind of validation for it, but would be great if you can confirm if it was this issue or something else.

**Review by wa0x6e — APPROVED** [review]
tAck

**Pull request merged**
