### PR TITLE
feat: support custom label for basic voting

### PR DESCRIPTION
**Pull request by bonustrack**
### Summary 

Closes: https://github.com/snapshot-labs/workflow/issues/89

- Make basic voting the default voting system
- Add icons for basic voting choices.
- Make choice label editable on basic voting.
- Allow offchain proposals to have 2 options for basic voting (no Abstain).

image

### Test plan
1. Create proposal on offchain space with custom basic choices, vote on it, edit your vote, check results.
2. 1. Create proposal on onchain space with custom basic choices, vote on it, check results.

### CODE REVIEW

**Comment by Sekhmet** [comment]
Should be good, just needs API to include latest changes.

**Comment by Sekhmet** [comment]
@bonustrack ready for review and testing.

**Review by bonustrack — COMMENTED** [review]
tACK that's perfect! (Can't approve the PR as I'm author)

**Review by Sekhmet — APPROVED** [review]
tACK

**Pull request merged**
