### PR TITLE
fix: use the new `autoLogin` function to silently login users

### PR DESCRIPTION
**Pull request by wa0x6e**
### Summary

Toward https://github.com/snapshot-labs/sx-monorepo/issues/478
Depends on https://github.com/snapshot-labs/lock/pull/121

This PR will use the new `autoLogin` function in the lock library, which will log in a previously logged user silently, without triggering any wallet prompt

For now, this PR is only fixing the issue with the injected (metamask) wallet, argent X fix coming in another PR

### How to test

1. yarn link a local version of lock, on the branch `feat-add-auto-connect-function`
2. `yarn dev`
3. You can log in and log out as usual
4. When logged in, refreshing the page will log you in automatically
5. When metamask wallet is locked, visiting the site will not open the metamask unlock prompt anymore
6. Clicking on "Log in" > "Metamask" should prompt to unlock metamask wallet

### CODE REVIEW

**Review by bonustrack — APPROVED** [review]
tACK

**Comment by bonustrack** [comment]
It works for EVM network but not Starknet, with Starknet the wallet get triggered not sure if that's expected

**Comment by wa0x6e** [comment]
> It works for EVM network but not Starknet, with Starknet the wallet get triggered not sure if that's expected

Yes, it's expected, starknet fix is coming in another later PR

**Review by bonustrack — APPROVED** [review]
tACK

**Comment by wa0x6e** [comment]
Waiting for new lock version before merging

**Comment by ChaituVR** [comment]
> Waiting for new lock version before merging

https://github.com/snapshot-labs/sx-monorepo/pull/847/files

**Pull request merged**
