### PR TITLE
chore: add extension suggestions

### PR DESCRIPTION
**Pull request by Sekhmet**
### Summary

This will add suggestions to install few useful VSCode extensions:
 - Vue
 - Tailwind CSS IntelliSense
 - ESLint
 - GitLens
 - EditorConfig
 - Prettier

### CODE REVIEW

**Comment by Sekhmet** [comment]
@pscott you can check if vscode suggests to install those extensions when you open sx-monorepo directory on this branch.

**Comment by Sekhmet** [comment]
lint failing because it's broken on master.

**Comment by pscott** [comment]
Can confirm it recommends the extensions.
Screenshot 2024-10-23 at 13 06 20
Screenshot 2024-10-23 at 13 06 25

**Review by pscott — APPROVED** [review]
tACK

**Review by wa0x6e — APPROVED** [review]
Screenshot 2024-10-23 at 15 15 25

Not getting the recommendation popup, but it detect the recommendation properly

**Pull request merged**
