### PR TITLE
fix: remove html to markdown conversion on user statement

### PR DESCRIPTION
**Pull request by wa0x6e**
### Summary

Fixes https://github.com/snapshot-labs/workflow/issues/242

This PR removes the HTML to Markdown conversion on user statement.

Conversion has issue when statement is already markdown formatted, as it's removing new line

### How to test

1. Go to https://snapshot.box/#/s:fabien.eth/profile/0xeF8305E140ac520225DAf050e2f71d5fBcC543e7
2. Markdown content should be formatted properly

### TODO 

- [x] Merge after https://github.com/snapshot-labs/snapshot-sequencer/pull/457

### CODE REVIEW

**Comment by ChaituVR** [comment]
But it show html now, is it ok?
image

**Comment by wa0x6e** [comment]
It's not supposed to show HTML, if the statement is converted to markdown.

And if the user has put some HTML himself, it's just keeping the same behavior as proposal: https://snapshot.box/#/s:test.wa0x6e.eth/proposal/0x87882ad4c46328cfd23e696c707d0e7dabc7153bf0888a01c81528b02c390241

**Review by ChaituVR — APPROVED** [review]
tAck

if html tags are expected to be shown

**Review by bonustrack — APPROVED** [review]
tACK

**Pull request merged**
