### PR TITLE
fix(ui): improve space cover dimensions

### PR DESCRIPTION
**Pull request by wa0x6e**
### Summary

Closes: https://github.com/snapshot-labs/stamp/issues/172

### Changes 

Only 1 change: increasing the fetched image height.
The other changes are just CSS cleaning and DRY-ing 

### How to test

1. Go to the /explore page, and a onchain space with cover image (ens, nostra)
2. The space cover dimension should be better

### CODE REVIEW

**Comment by bonustrack** [comment]
Can you also use smaller image size for the cover on the page Explore? I did that on #403

**Comment by wa0x6e** [comment]
Maybe let's go with your PR if going with the different image size in props

**Comment by bonustrack** [comment]
I prefer your way actually with an image instead of a background image, this way you can open the image easily.

**Comment by wa0x6e** [comment]
Added. Also used a different smaller size for `sm`, still 2x bigger than actual size, for retina display.

**Review by Sekhmet — APPROVED** [review]
tACK

**Pull request merged**
