### PR TITLE
Revert "feat: vote modal with reason (#427)"

### PR DESCRIPTION
**Pull request by Sekhmet**
This reverts commit ad6fc9e2fb8c7c6f95b89e29baccafd2f710926a.

It has two issues:
- We don't show reason right now so it doesn't make sense to ask users for it.
- VP no longer gets computed at specific block:
https://github.com/snapshot-labs/sx-monorepo/blob/ad6fc9e2fb8c7c6f95b89e29baccafd2f710926a/apps/ui/src/stores/votingPowers.ts#L59

### CODE REVIEW

**Review by wa0x6e — APPROVED** [review]
utAck

**Comment by bonustrack** [comment]
For the record there is also an issue where even if the reason is empty it will pin it on IPFS and add it to the vote

**Review by bonustrack — APPROVED** [review]
utACK, wasn't able to test the whole flow I imagine due to Herodotus issue

**Comment by Sekhmet** [comment]
Reverting 78044d356490e7741cea2b5e7cfefc32086d9284 as well as it was fixing merge conflict from this PR as well.

**Pull request merged**
