### PR TITLE
fix: fix hidden choice filter dropdown in votes page

### PR DESCRIPTION
**Pull request by wa0x6e**
### Summary

Closes: https://github.com/snapshot-labs/workflow/issues/239

Fix the choice filter dropdown not appearing on votes page, becuase of overflow hidden

This PR will use the Float library, to show the dropdown in a portal

### How to test

1. Go to a proposal with basic choice
2. Go to votes page
3. The choice filter dropdown should be  visible on click

### CODE REVIEW

**Comment by ChaituVR** [comment]
Choice filter is hidden somehow 
Untitled 4

**Comment by ChaituVR** [comment]
ahh desc. should've mentioned SX spaces

**Review by ChaituVR — APPROVED** [review]
tAck

**Comment by wa0x6e** [comment]
mhhhh should work on all basic choice proposals

**Comment by wa0x6e** [comment]
> mhhhh should work on all basic choice proposals

Finally, it's not the case, but it should, nothing preventing this filter from working on both onchain and offchain, will open an issue

**Pull request merged**
